=== justinquinnb/OneFeed/resources/addon.xsd
<xs:schema
        attributeFormDefault="unqualified"
        elementFormDefault="qualified"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="addon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="addonInfo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="meta">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="addonName"/>
                                        <xs:element type="xs:string" name="addonAuthor"/>
                                        <xs:element type="xs:string" name="addonUrl"/>
                                        <xs:element type="xs:string" name="addonVersion"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="developer">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="grabberFileName"/>
                                        <xs:element type="xs:string" name="processorFileName"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sourceInfo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="sourceName"/>
                            <xs:element type="xs:string" name="sourceAuthor"/>
                            <xs:element type="xs:string" name="sourceHomepageUrl"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== justinquinnb/OneFeed/src/data_sources/github/addon.xml
<?xml version="1.0" encoding="UTF-8" ?>
<addon
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="/resources/addon.xsd">
    <addonInfo>
        <meta>
            <addonName>GitHub Grabber</addonName>
            <addonAuthor>Justin Quinn</addonAuthor>
            <addonUrl>https://github.com/justinquinnb/OneFeed</addonUrl>
            <addonVersion>0.0.1</addonVersion>
        </meta>
        <developer>
            <grabberFileName>GitHubApi.java</grabberFileName>
            <processorFileName>GitHubProcessor.java</processorFileName>
        </developer>
    </addonInfo>
    <sourceInfo>
        <sourceName>GitHub</sourceName>
        <sourceAuthor>Microsoft</sourceAuthor>
        <sourceHomepageUrl>https://github.com/</sourceHomepageUrl>
    </sourceInfo>
</addon>
